#!/bin/bash

PROTO_IN="$1"
JAVA_OUT="$2"
TMP_DIR=`mktemp -d`

mkdir -p "$JAVA_OUT"
mkdir -p "$TMP_DIR"

protoc \
  --java_out="$TMP_DIR" \
  --proto_path="$PROTO_IN" \
  "$PROTO_IN"/*.proto

# Use checksums to compare, and don't preserve timestamp.
# We want the destination timestamp to be unchanged if
# the destination file is unchanged.
rsync -curpgo --delete "$TMP_DIR"/ "$JAVA_OUT"/
rm -r "$TMP_DIR"

