import os
import sys
import subprocess
import signal
import threading

# TODO(tpondich): This is not well encapsulated.
logfile = None
proc1 = None

def timeout_handler():
    global logfile
    global proc1
    
    logfile.write("************************ TIMEOUT\n")
    if proc1:
        logfile.write("************************ KILLING PSTOEDIT\n")
        proc1.terminate()
    logfile.close()

def run_pstoedit(key, format, data, tmpdir, tmpfile, timeout):
    t = threading.Timer(timeout, timeout_handler)
    t.start()
    
    logfile = open(tmpdir + tmpfile + '.log', 'w')
    
    psin = ''
    # WARNING: ARBITRARY CODE EXECUTION MAY BE POSSIBLE HERE!
    # PSTOEDIT DOES NOT GIVE ACCESS TO ALL THE NICE GS FLAGS FOR SAFETY.
    additional_args = ['/usr/bin/pstoedit', '-f', 'plot-svg']
    if format == 'svg':
        psin = data
    else:
        logfile.write('Invalid format: ' + format)
        logfile.close()
        return '' # TODO(tpondich): exception, catch return error to appengine.

    logfile.write("************************ INPUT PS\n")
    logfile.write(psin)
    logfile.flush()
    logfile.write("************************ RUNNING PSTOEDIT\n")
    proc1 = subprocess.Popen(additional_args,
                           stdin=subprocess.PIPE,
                           stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE)
    
    (gsout, gserr) = proc1.communicate(psin)
    
    logfile.write("\n************************ PSTOEDIT STDERR\n")
    if gserr:
        logfile.write(gserr)
        logfile.flush()
    
    logfile.write("\n************************ DONE\n")
    logfile.close()
    
    t.cancel()
    
    # The svg generated by pstoedit has screwed up dimensions
    # This hack fixes them
    ps = str(psin)
    dims = ps[ps.find('[') + 1 : ps.find(']')].split(' ')
    width = int(dims[0])
    height = int(dims[1])
    gsout = str(gsout)
    gsout = gsout.replace('width="8in"', '')
    gsout = gsout.replace('height="8in"', '')
    gsout = gsout.replace('viewBox="0 0 1 1"', 'viewBox="0 0 ' + str(width) + ' ' + str(height) + '"')
    gsout = gsout.replace('transform="translate(-0.03125,1.1875)', 'transform="translate(0,' + str(height) + ')')
    gsout = gsout.replace('scale(0.0017361)', '')
    gsout = gsout.replace('preserveAspectRatio="none"', 'preserveAspectRatio="xMidYMin"')
    
    return gsout
